name: Build Project
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: log
        run: |
          cd \actions-runner
          mkdir actionsRunnerTest
          echo "test" >> testlogtest.txt
          echo "Current location: %cd%" >> testlogtest.txt
          echo "secrets: %{{secrets.PATH}}" >> testlogtest.txt

          .\test.sh

      # - name: move
      #   run: |
      #     cd /d D:\
      #     cd \dev\cicdTest
      #     echo "Current location: %cd%" >> testlogtest.txt
      #     echo "Current location: %USERNAME%" >> testlogtest.txt

      - name: git update and check changes
        id: check-changes
        run: |
          cd /d D:\
          cd \dev\cicdTest
          git fetch
          git pull
          git diff --name-only HEAD~1 > changes.txt
          set "changes="
          for /f %%i in (changes.txt) do set "changes=!changes! %%i"
          echo "changes=%%changes%%" > $GITHUB_ENV

      - name: Install dependencies
        run: |
          if not defined changes (
            echo package.json에 변경 사항이 없습니다. npm install을 건너뜁니다.
          ) else (
            echo %changes% | find /C /I "package.json" > nul
            if errorlevel 1 (
              echo package.json에 변경 사항이 없습니다. npm install을 건너뜁니다.
            ) else (
              cd /d D:\
              cd \dev\cicdTest
              npm ci
            )
          )


      - name: npm build
        run: |
          cd /d D:\
          cd \dev\cicdTest
          npm run build
          .\test.ps1

      - name: copy and move
        run: |
          cd /d D:\
          cd \dev\cicdTest
          xcopy "./dist" "C:\cd" /E /I /Y
