name: Build Project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: log
        run: |
          cd \actions-runner
          mkdir actionsRunnerTest
          echo "test" >> testlogtest.txt
          echo "Current location: %cd%" >> testlogtest.txt
          echo "secrets: %{{secrets.PATH}}" >> testlogtest.txt

          .\test.sh
      - name: move
        run: |
          cd /d D:\
          cd \dev\cicdTest
          echo "Current location: %cd%" >> testlogtest.txt
          echo "Current location: %USERNAME%" >> testlogtest.txt
      - name: git update
        run: |
          cd /d D:\
          cd \dev\cicdTest
          git fetch
          git pull
      - name: npm install
        run: |
          cd /d D:\
          cd \dev\cicdTest
          npm ci
      - name: npm install build
        run: |
          cd /d D:\
          cd \dev\cicdTest
          npm run build
          .\test.ps1
      - name: npm install build
        run: |
          cd /d D:\
          cd \dev\cicdTest
          .\test.ps1
      - name: copy and move
        run: |
          cd /d D:\
          cd \dev\cicdTest
          xcopy "./dist" "C:\cd" /E /I /Y
