name: Build Project
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: test
        run: |
          cd /actions-runner
          bash ./test.ps1 # 이제야 되는거니..
