name: Build Project
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: test
        run: |
          cd /d D:\
          cd \dev\cicdTest
          bash \bash\test.sh
