
# name: Build Project
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: self-hosted
#     defaults:
#       run:
#         shell: cmd
#     steps:
#       - name: log
#         run: ./test.sh
# #       - name: move directory
# #         run: cd D:\dev\cicdTest
# #         shell: bash
# #       - name: Fetch repository
# #         run: git fetch origin
# #         shell: bash
# #       - name: Pull latest changes
# #         run: git pull origin main
# #         shell: bash
# #       - name: Build project
# #         run: |
# #           # Commands to build the project
# #           # For example:
# #           #cd project_directory
# #           #npm install
# #           #npm run build
# #           echo "test"
# #         shell: bash
#     env:
#       MY_LABEL: test
name: Build Project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: log
        run: |
          cd \actions-runner
          mkdir actionsRunnerTest
          echo "test" >> log.txt
          echo "Current location: $current_location" >> log.txt
          .\test.sh
          cd /d D:\
          cd \dev\cicdTest
          echo "test" >> testlogtest.txt
          git fetch
          git pull
          npm i
          npm run build
          