
# name: Build Project
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: self-hosted
#     defaults:
#       run:
#         shell: cmd
#     steps:
#       - name: log
#         run: ./test.sh
# #       - name: move directory
# #         run: cd D:\dev\cicdTest
# #         shell: bash
# #       - name: Fetch repository
# #         run: git fetch origin
# #         shell: bash
# #       - name: Pull latest changes
# #         run: git pull origin main
# #         shell: bash
# #       - name: Build project
# #         run: |
# #           # Commands to build the project
# #           # For example:
# #           #cd project_directory
# #           #npm install
# #           #npm run build
# #           echo "test"
# #         shell: bash
#     env:
#       MY_LABEL: test
name: Build Project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - name: log
        run: |
          cd \actions-runner
          mkdir actionsRunnerTest
          echo "test" >> log.txt
          echo "Current location: %cd%" >> log.txt
          .\test.sh
      - name: move
        run: |
          cd /d D:\
          cd \dev\cicdTest
          echo "Current location: %cd%" >> testlogtest.txt
          echo "Current location: %USERNAME%" >> testlogtest.txt
      - name: git update
        run: |
          cd /d D:\
          cd \dev\cicdTest
          git fetch
          git pull
      - name: npm install and build
        run: |
          cd /d D:\
          cd \dev\cicdTest
          npm run build
          .\test.sh