name: Build Project
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: C:\Program Files\Git\git-bash.exe
    steps:
      - name: test
        run: |
          cd "/c/actions-runner"
          bash test.sh # 이제야 되는거니..
